### PR TITLE
Bugfix 149 fix react router paths

### LINKED ISSUE #149: Fix react router paths

### PR DESCRIPTION
**Pull request by EVP1989**
Resolves #149

### CODE REVIEW

File: src/components/CreateCampaign.tsx [hunk 1]
```diff
@@ -73,8 +73,7 @@ class CreateCampaign extends React.Component<Props, State> {
 
   public render () {
     if (this.state.redirect) {
-      redirect(`/campaigns/${this.state.campaignId}`);
-      return null;
+      return <Navigate replace={true} to={`/campaigns/${this.state.campaignId}`}/>;
```
Comment (Jdallos) [inline src/components/CreateCampaign.tsx:76]:
```suggestion
      return <Navigate replace={true} to={`/campaigns/${this.state.campaignId}`} />;
```

Comment (Jdallos) [reply src/components/CreateCampaign.tsx:76]: Could add this space for all the navigates if preferred?

File: src/components/EditCampaign.tsx [hunk 2]
```diff
@@ -86,8 +86,7 @@ class EditCampaign extends React.Component<Props, State> {
 
   public render () {
     if (this.state.redirect) {
-      redirect(`/campaigns`);
-      return null;
+      return <Navigate replace={true} to={`/campaigns`}/>;
```
Comment (Jdallos) [inline src/components/EditCampaign.tsx:89]: No variable in the 'to', so do you need the template literal, could it just be a string as in other components?

File: src/components/EditCutPacking.tsx [hunk 3]
```diff
@@ -141,8 +141,7 @@ class EditCutPacking extends React.Component<Props, State> {
     } = this.state;
 
     if (this.state.redirect) {
-      redirect(`/cutPackings`);
-      return null;
+      return <Navigate replace={true} to={`/cutPackings`}/>;
```
Comment (Jdallos) [inline src/components/EditCutPacking.tsx:144]: No variable in the 'to', so do you need the template literal, could it just be a string as in other components?

**Review by Jdallos — APPROVED** [review]
